### ISSUE TITLE
When i run ./aungrecon.sh   coming this error please help to run this command 

### ISSUE THREAD

**Issue by nak000** [aungsanoo-usa/aungrecon#1]
![image](https://github.com/user-attachments/assets/7f57bf91-77d4-4998-9581-4b4c574e2544)

**Comment by rat1o1** [comment]
got same error

**Comment by nak000** [comment]
Hi, bro thanks for responding.  But again same error
![Screenshot 2024-11-30 232038](https://github.com/user-attachments/assets/db305eca-f4f9-4cec-81ab-28ad49c9ee7c)

**Comment by aungsanoo-usa** [comment]
That is not error bro .. You dont updated new one ..please run again install.sh ..i added some tools  😁

**Comment by nak000** [comment]
ok bro

**Comment by nak000** [comment]
now the problem is resolved bro thank you so much, bro...

**Comment by SvenBrakhoven** [comment]
### Please help me fix this I am getting the following errors when i run ./aungrecon.sh

```
[+] GitHub token loaded successfully.
[!] Invalid or expired GitHub token. Please update github_token.txt.
Checking internet connectivity...
Connection to google.com: OK
[!] The following tools are missing: paramspider uro porch-pirate metafinder emailfinder whois.                                                                                              
[?] Would you like to install them now? (y/n): y  
```
and after clicking yes am getting  incomplete installation with errors.I have also tried ./install.sh  and the installation runs and encounters same errors before the message; "Installation completed (with warnings, if any)!"

Here are the errors encountered during installation;

**Installation process showing errors**

```
└─$ ./install.sh  
##########################################################
##### Welcome to the AungRecon dependency installer #####                                                                                                                                    
##########################################################                                                                                                                                   
                                                                                                                                                                                             
Hit:1 http://http.kali.org/kali kali-rolling InRelease                                                                                                                                       
Hit:2 https://dl.google.com/linux/chrome/deb stable InRelease                                           
1156 packages can be upgraded. Run 'apt list --upgradable' to see them.
Installing programming languages and essential packages
golang-go is already the newest version (2:1.23~2).                                                                                                                                          
cmake is already the newest version (3.30.5-1).
jq is already the newest version (1.7.1-3+b1).
whatweb is already the newest version (0.5.5-1).
ffuf is already the newest version (2.1.0-1+b4).
nikto is already the newest version (1:2.5.0+git20230114.90ff645-0kali1).
curl is already the newest version (8.11.1-1).
python3-pip is already the newest version (24.3.1+dfsg-1).
unzip is already the newest version (6.0-28).
wget is already the newest version (1.24.5-2+b1).
Summary:
  Upgrading: 0, Installing: 0, Removing: 0, Not Upgrading: 1156
Installing Google Chrome
--2025-01-06 05:53:55--  https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb                                                                                           
Resolving dl.google.com (dl.google.com)... 142.251.32.78, 2607:f8b0:400b:80c::200e
Connecting to dl.google.com (dl.google.com)|142.251.32.78|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 112770956 (108M) [application/x-debian-package]
Saving to: ‘google-chrome-stable_current_amd64.deb’

google-chrome-stable_current_amd64.deb          100%[====================================================================================================>] 107.55M  2.33MB/s    in 54s     

2025-01-06 05:54:51 (1.99 MB/s) - ‘google-chrome-stable_current_amd64.deb’ saved [112770956/112770956]

(Reading database ... 242809 files and directories currently installed.)
Preparing to unpack google-chrome-stable_current_amd64.deb ...
Unpacking google-chrome-stable (131.0.6778.204-1) over (131.0.6778.204-1) ...
Setting up google-chrome-stable (131.0.6778.204-1) ...
Processing triggers for kali-menu (2023.2.3) ...
Processing triggers for desktop-file-utils (0.26-1) ...
Processing triggers for mailcap (3.70+nmu1) ...
Processing triggers for man-db (2.11.2-2) ...
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
0 upgraded, 0 newly installed, 0 to remove and 1156 not upgraded.
Installing ChromeDriver version 128.0.6613.119
--2025-01-06 05:55:09--  https://storage.googleapis.com/chrome-for-testing-public/128.0.6613.119/linux64/chromedriver-linux64.zip                                                            
Resolving storage.googleapis.com (storage.googleapis.com)... 142.251.41.59, 142.251.32.91, 172.217.1.27, ...
Connecting to storage.googleapis.com (storage.googleapis.com)|142.251.41.59|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 9363514 (8.9M) [application/zip]
Saving to: ‘chromedriver-linux64.zip’

chromedriver-linux64.zip                        100%[====================================================================================================>]   8.93M  2.36MB/s    in 6.3s    

2025-01-06 05:55:19 (1.43 MB/s) - ‘chromedriver-linux64.zip’ saved [9363514/9363514]

Archive:  chromedriver-linux64.zip
  inflating: chromedriver-linux64/LICENSE.chromedriver  
  inflating: chromedriver-linux64/THIRD_PARTY_NOTICES.chromedriver  
  inflating: chromedriver-linux64/chromedriver  
Installing Go-based tools
Installing v2                                                                                                                                                                                
cp: cannot stat '/home/dada/go/bin/v2': No such file or directory                                                                                                                            
Failed to move v2 to /usr/local/bin
Installing subfinder
Installing httpx                                                                                                                                                                             
Installing gau                                                                                                                                                                               
Installing gf                                                                                                                                                                                
Installing Gxss                                                                                                                                                                              
Installing kxss                                                                                                                                                                              
Installing qsreplace                                                                                                                                                                         
Installing subzy                                                                                                                                                                             
Installing anew                                                                                                                                                                              
Installing nuclei                                                                                                                                                                            
Installing katana                                                                                                                                                                            
Installing gitdorks_go                                                                                                                                                                       
Installing unfurl                                                                                                                                                                            
Installing enumerepo                                                                                                                                                                         
Installing crlfuzz                                                                                                                                                                           
Installing naabu                                                                                                                                                                             
github.com/gopacket/gopacket/pcap                                                                                                                                                            
# github.com/gopacket/gopacket/pcap
../../../go/pkg/mod/github.com/gopacket/gopacket@v1.2.0/pcap/pcap_unix.go:35:10: fatal error: pcap.h: No such file or directory
   35 | #include <pcap.h>
      |          ^~~~~~~~
compilation terminated.
Failed to install Go tool: naabu
cp: cannot stat '/home/dada/go/bin/naabu': No such file or directory
Failed to move naabu to /usr/local/bin
Installing jsleak
Installing Python-based tools (porch-pirate, emailfinder)                                                                                                                                    
Defaulting to user installation because normal site-packages is not writeable                                                                                                                
Collecting porch-pirate
  Using cached porch_pirate-0.0.1-py3-none-any.whl.metadata (6.3 kB)
Collecting emailfinder
  Using cached emailfinder-0.3.0b0-py3-none-any.whl.metadata (1.6 kB)
Collecting metafinder
  Using cached metafinder-1.2.tar.gz (11 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-n43s_szd/metafinder_0874495fb377492b8160a0c49532abf6/setup.py", line 2, in <module>
          from setuptools import setup, find_packages
      ImportError: cannot import name 'setup' from 'setuptools' (unknown location)
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
Failed to install Python tools
Fixing emailfinder banner issue
Traceback (most recent call last):                                                                                                                                                           
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'emailfinder'
[!] Emailfinder module not found.
Cloning repositories and installing dependencies
Cloning bsqli...                                                                                                                                                                             
fatal: destination path '/home/dada/Desktop/workings-kali/aungrecon/tools/bsqli' already exists and is not an empty directory.
Failed to clone bsqli.
Cloning Corsy...
fatal: destination path '/home/dada/Desktop/workings-kali/aungrecon/tools/Corsy' already exists and is not an empty directory.
Failed to clone Corsy.
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: requests in /usr/lib/python3/dist-packages (from -r requirements.txt (line 1)) (2.28.1)
Cloning SwaggerSpy...
fatal: destination path '/home/dada/Desktop/workings-kali/aungrecon/tools/SwaggerSpy' already exists and is not an empty directory.
Failed to clone SwaggerSpy.
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: requests in /usr/lib/python3/dist-packages (from -r requirements.txt (line 1)) (2.28.1)
Requirement already satisfied: colorama in /usr/lib/python3/dist-packages (from -r requirements.txt (line 2)) (0.4.6)
Cloning paramspider...
fatal: destination path '/home/dada/Desktop/workings-kali/aungrecon/tools/paramspider' already exists and is not an empty directory.
Failed to clone paramspider.
Cloning dorks_hunter...
fatal: destination path '/home/dada/Desktop/workings-kali/aungrecon/tools/dorks_hunter' already exists and is not an empty directory.
Failed to clone dorks_hunter.
Defaulting to user installation because normal site-packages is not writeable
Collecting argparse (from -r requirements.txt (line 1))
  Using cached argparse-1.4.0-py2.py3-none-any.whl.metadata (2.8 kB)
Requirement already satisfied: tldextract in /home/dada/.local/lib/python3.12/site-packages (from -r requirements.txt (line 2)) (5.1.3)
Requirement already satisfied: google in /home/dada/.local/lib/python3.12/site-packages (from -r requirements.txt (line 3)) (3.0.0)
Requirement already satisfied: fake_useragent in /home/dada/.local/lib/python3.12/site-packages (from -r requirements.txt (line 4)) (2.0.3)
Requirement already satisfied: idna in /usr/lib/python3/dist-packages (from tldextract->-r requirements.txt (line 2)) (3.3)
Requirement already satisfied: requests>=2.1.0 in /usr/lib/python3/dist-packages (from tldextract->-r requirements.txt (line 2)) (2.28.1)
Requirement already satisfied: requests-file>=1.4 in /home/dada/.local/lib/python3.12/site-packages (from tldextract->-r requirements.txt (line 2)) (2.1.0)
Requirement already satisfied: filelock>=3.0.8 in /home/dada/.local/lib/python3.12/site-packages (from tldextract->-r requirements.txt (line 2)) (3.16.1)
Requirement already satisfied: beautifulsoup4 in /usr/lib/python3/dist-packages (from google->-r requirements.txt (line 3)) (4.11.2)
Using cached argparse-1.4.0-py2.py3-none-any.whl (23 kB)
Installing collected packages: argparse
Successfully installed argparse-1.4.0
Cloning gFpattren...
fatal: destination path '/home/dada/Desktop/workings-kali/aungrecon/tools/gFpattren' already exists and is not an empty directory.
Failed to clone gFpattren.
Cloning urldedupe...
fatal: destination path '/home/dada/Desktop/workings-kali/aungrecon/tools/urldedupe' already exists and is not an empty directory.
Failed to clone urldedupe.
Cloning Spoofy...
fatal: destination path '/home/dada/Desktop/workings-kali/aungrecon/tools/Spoofy' already exists and is not an empty directory.
Failed to clone Spoofy.
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: colorama in /usr/lib/python3/dist-packages (from -r requirements.txt (line 1)) (0.4.6)
Requirement already satisfied: dnspython>=2.2.1 in /usr/lib/python3/dist-packages (from -r requirements.txt (line 2)) (2.3.0)
Requirement already satisfied: tldextract in /home/dada/.local/lib/python3.12/site-packages (from -r requirements.txt (line 3)) (5.1.3)
Requirement already satisfied: pandas in /home/dada/.local/lib/python3.12/site-packages (from -r requirements.txt (line 4)) (2.2.3)
Requirement already satisfied: openpyxl in /home/dada/.local/lib/python3.12/site-packages (from -r requirements.txt (line 5)) (3.1.5)
Requirement already satisfied: idna in /usr/lib/python3/dist-packages (from tldextract->-r requirements.txt (line 3)) (3.3)
Requirement already satisfied: requests>=2.1.0 in /usr/lib/python3/dist-packages (from tldextract->-r requirements.txt (line 3)) (2.28.1)
Requirement already satisfied: requests-file>=1.4 in /home/dada/.local/lib/python3.12/site-packages (from tldextract->-r requirements.txt (line 3)) (2.1.0)
Requirement already satisfied: filelock>=3.0.8 in /home/dada/.local/lib/python3.12/site-packages (from tldextract->-r requirements.txt (line 3)) (3.16.1)
Requirement already satisfied: numpy>=1.26.0 in /home/dada/.local/lib/python3.12/site-packages (from pandas->-r requirements.txt (line 4)) (2.2.1)
Requirement already satisfied: python-dateutil>=2.8.2 in /home/dada/.local/lib/python3.12/site-packages (from pandas->-r requirements.txt (line 4)) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/lib/python3/dist-packages (from pandas->-r requirements.txt (line 4)) (2022.7.1)
Requirement already satisfied: tzdata>=2022.7 in /home/dada/.local/lib/python3.12/site-packages (from pandas->-r requirements.txt (line 4)) (2024.2)
Requirement already satisfied: et-xmlfile in /home/dada/.local/lib/python3.12/site-packages (from openpyxl->-r requirements.txt (line 5)) (2.0.0)
Requirement already satisfied: six>=1.5 in /usr/lib/python3/dist-packages (from python-dateutil>=2.8.2->pandas->-r requirements.txt (line 4)) (1.16.0)
Cloning xss_scanner...
fatal: destination path '/home/dada/Desktop/workings-kali/aungrecon/tools/xss_scanner' already exists and is not an empty directory.
Failed to clone xss_scanner.
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: selenium in /home/dada/.local/lib/python3.12/site-packages (from -r requirements.txt (line 1)) (4.27.1)
Requirement already satisfied: rich in /usr/lib/python3/dist-packages (from -r requirements.txt (line 2)) (13.3.1)
Requirement already satisfied: colorama in /usr/lib/python3/dist-packages (from -r requirements.txt (line 3)) (0.4.6)
Requirement already satisfied: webdriver-manager in /home/dada/.local/lib/python3.12/site-packages (from -r requirements.txt (line 4)) (4.0.2)
Requirement already satisfied: urllib3 in /usr/lib/python3/dist-packages (from -r requirements.txt (line 5)) (1.26.12)
Requirement already satisfied: prompt_toolkit in /usr/lib/python3/dist-packages (from -r requirements.txt (line 6)) (3.0.36)
Requirement already satisfied: trio~=0.17 in /home/dada/.local/lib/python3.12/site-packages (from selenium->-r requirements.txt (line 1)) (0.28.0)
Requirement already satisfied: trio-websocket~=0.9 in /home/dada/.local/lib/python3.12/site-packages (from selenium->-r requirements.txt (line 1)) (0.11.1)
Requirement already satisfied: certifi>=2021.10.8 in /usr/lib/python3/dist-packages (from selenium->-r requirements.txt (line 1)) (2022.9.24)
Requirement already satisfied: typing_extensions~=4.9 in /usr/lib/python3/dist-packages (from selenium->-r requirements.txt (line 1)) (4.12.2)
Requirement already satisfied: websocket-client~=1.8 in /home/dada/.local/lib/python3.12/site-packages (from selenium->-r requirements.txt (line 1)) (1.8.0)
Requirement already satisfied: markdown-it-py<3.0.0,>=2.1.0 in /usr/lib/python3/dist-packages (from rich->-r requirements.txt (line 2)) (2.1.0)
Requirement already satisfied: pygments<3.0.0,>=2.14.0 in /usr/lib/python3/dist-packages (from rich->-r requirements.txt (line 2)) (2.14.0)
Requirement already satisfied: requests in /usr/lib/python3/dist-packages (from webdriver-manager->-r requirements.txt (line 4)) (2.28.1)
Requirement already satisfied: python-dotenv in /usr/lib/python3/dist-packages (from webdriver-manager->-r requirements.txt (line 4)) (0.21.0)
Requirement already satisfied: packaging in /home/dada/.local/lib/python3.12/site-packages (from webdriver-manager->-r requirements.txt (line 4)) (24.2)
Requirement already satisfied: mdurl~=0.1 in /usr/lib/python3/dist-packages (from markdown-it-py<3.0.0,>=2.1.0->rich->-r requirements.txt (line 2)) (0.1.2)
Requirement already satisfied: attrs>=23.2.0 in /home/dada/.local/lib/python3.12/site-packages (from trio~=0.17->selenium->-r requirements.txt (line 1)) (24.3.0)
Requirement already satisfied: sortedcontainers in /home/dada/.local/lib/python3.12/site-packages (from trio~=0.17->selenium->-r requirements.txt (line 1)) (2.4.0)
Requirement already satisfied: idna in /usr/lib/python3/dist-packages (from trio~=0.17->selenium->-r requirements.txt (line 1)) (3.3)
Requirement already satisfied: outcome in /home/dada/.local/lib/python3.12/site-packages (from trio~=0.17->selenium->-r requirements.txt (line 1)) (1.3.0.post0)
Requirement already satisfied: sniffio>=1.3.0 in /home/dada/.local/lib/python3.12/site-packages (from trio~=0.17->selenium->-r requirements.txt (line 1)) (1.3.1)
Requirement already satisfied: wsproto>=0.14 in /home/dada/.local/lib/python3.12/site-packages (from trio-websocket~=0.9->selenium->-r requirements.txt (line 1)) (1.2.0)
Requirement already satisfied: PySocks!=1.5.7,<2.0,>=1.5.6 in /home/dada/.local/lib/python3.12/site-packages (from urllib3[socks]<3,>=1.26->selenium->-r requirements.txt (line 1)) (1.7.1)
Requirement already satisfied: h11<1,>=0.9.0 in /usr/lib/python3/dist-packages (from wsproto>=0.14->trio-websocket~=0.9->selenium->-r requirements.txt (line 1)) (0.14.0)
Cloning SecretFinder...
fatal: destination path '/home/dada/Desktop/workings-kali/aungrecon/tools/SecretFinder' already exists and is not an empty directory.
Failed to clone SecretFinder.
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: requests_file in /home/dada/.local/lib/python3.12/site-packages (from -r requirements.txt (line 1)) (2.1.0)
Requirement already satisfied: requests in /usr/lib/python3/dist-packages (from -r requirements.txt (line 2)) (2.28.1)
Requirement already satisfied: jsbeautifier in /home/dada/.local/lib/python3.12/site-packages (from -r requirements.txt (line 3)) (1.15.1)
Requirement already satisfied: lxml in /usr/lib/python3/dist-packages (from -r requirements.txt (line 4)) (5.3.0)
Requirement already satisfied: six>=1.13.0 in /usr/lib/python3/dist-packages (from jsbeautifier->-r requirements.txt (line 3)) (1.16.0)
Requirement already satisfied: editorconfig>=0.12.2 in /home/dada/.local/lib/python3.12/site-packages (from jsbeautifier->-r requirements.txt (line 3)) (0.17.0)
Cloning misconfig-mapper...
fatal: destination path '/home/dada/Desktop/workings-kali/aungrecon/tools/misconfig-mapper' already exists and is not an empty directory.
Failed to clone misconfig-mapper.
Cloning lfi_scanner...
fatal: destination path '/home/dada/Desktop/workings-kali/aungrecon/tools/lfi_scanner' already exists and is not an empty directory.
Failed to clone lfi_scanner.
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: requests in /usr/lib/python3/dist-packages (from -r requirements.txt (line 1)) (2.28.1)
Requirement already satisfied: colorama in /usr/lib/python3/dist-packages (from -r requirements.txt (line 2)) (0.4.6)
Requirement already satisfied: urllib3 in /usr/lib/python3/dist-packages (from -r requirements.txt (line 3)) (1.26.12)
Cloning LeakSearch...
fatal: destination path '/home/dada/Desktop/workings-kali/aungrecon/tools/LeakSearch' already exists and is not an empty directory.
Failed to clone LeakSearch.
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: urllib3 in /usr/lib/python3/dist-packages (from -r requirements.txt (line 1)) (1.26.12)
Collecting argparse (from -r requirements.txt (line 2))
  Using cached argparse-1.4.0-py2.py3-none-any.whl.metadata (2.8 kB)
Collecting tabulate (from -r requirements.txt (line 3))
  Using cached tabulate-0.9.0-py3-none-any.whl.metadata (34 kB)
Collecting neotermcolor (from -r requirements.txt (line 4))
  Using cached neotermcolor-2.0.10.tar.gz (5.4 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [7 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-91pvbx8y/neotermcolor_217f4dc90d1944c5b87e95d9b9b7281c/setup.py", line 8, in <module>
          setuptools.setup(
          ^^^^^^^^^^^^^^^^
      AttributeError: module 'setuptools' has no attribute 'setup'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
Failed to install dependencies for LeakSearch.
Cloning priv8-Nuclei...
fatal: destination path '/home/dada/Desktop/workings-kali/aungrecon/tools/priv8-Nuclei' already exists and is not an empty directory.
Failed to clone priv8-Nuclei.
Copying GF patterns...
Installing Misconfig Mapper...                                                                                                                                                               
[!] Misconfig Mapper already exists. Skipping clone.                                                                                                                                         
[+] Building Misconfig Mapper binary...
[+] Updating Misconfig Mapper templates...                                                                                                                                                   
[+] Info: Pulling latest services and saving in templates/services.json
[+] Info: Successfully pulled the latest templates!
Installing gitdorks_go...
[+] gitdorks_go is already installed.                                                                                                                                                        
Setting up paramspider
Defaulting to user installation because normal site-packages is not writeable                                                                                                                
Processing /home/dada/Desktop/workings-kali/aungrecon/tools/paramspider
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/home/dada/Desktop/workings-kali/aungrecon/tools/paramspider/setup.py", line 1, in <module>
          from setuptools import setup, find_packages
      ImportError: cannot import name 'setup' from 'setuptools' (unknown location)
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
Failed to install paramspider
mv: cannot stat '/home/dada/.local/bin/paramspider': No such file or directory
Failed to move paramspider to /usr/local/bin
Setting up urldedupe
CMake Error: The current CMakeCache.txt directory /home/dada/Desktop/workings-kali/aungrecon/tools/urldedupe/CMakeCache.txt is different than the directory /home/dada/Documents/workings-kali/aungrecon/tools/urldedupe where CMakeCache.txt was created. This may result in binaries being created in the wrong place. If you are not sure, reedit the CMakeCache.txt
CMake Error: The source "/home/dada/Desktop/workings-kali/aungrecon/tools/urldedupe/CMakeLists.txt" does not match the source "/home/dada/Documents/workings-kali/aungrecon/tools/urldedupe/CMakeLists.txt" used to generate cache.  Re-run cmake with a different source directory.
Failed to run CMake for urldedupe
/bin/sh: 1: cd: can't cd to /home/dada/Documents/workings-kali/aungrecon/tools/urldedupe
make[2]: *** [CMakeFiles/urldedupe.dir/build.make:156: CMakeFiles/urldedupe.dir/depend] Error 2
make[1]: *** [CMakeFiles/Makefile2:82: CMakeFiles/urldedupe.dir/all] Error 2
make: *** [Makefile:91: all] Error 2
Failed to compile urldedupe
mv: cannot stat '/home/dada/Desktop/workings-kali/aungrecon/tools/urldedupe/urldedupe': No such file or directory
Failed to move urldedupe to /usr/local/bin
Installing Python-based tools (uro, pystyle)
Collecting uro                                                                                                                                                                               
  Using cached uro-1.0.1.tar.gz (10.0 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-tyge7r4l/uro_2f463ddb508c4c65a5bb0e6b07301738/setup.py", line 3, in <module>
          from setuptools import setup, find_packages
      ImportError: cannot import name 'setup' from 'setuptools' (unknown locati
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem wi
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
Failed to install Python tools
mv: cannot stat '/home/dada/.local/bin/uro': No such file or directory
Failed to move uro to /usr/local/bin
Installation completed (with warnings, if any)!

```
